spring:
  application:
    name: service-demo1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id}:${server.port}
        ip-address: true
server:
  port: 9001